### ISSUE TITLE
BAV99 проблема с частями на схеме

### ISSUE THREAD

**Issue by Assamber** [sintech/Flip-Dot-Display#1]
![image](https://user-images.githubusercontent.com/24959102/110804496-46862f80-8291-11eb-87af-5b2230601764.png)

Если обратить внимание на подписи пинов у диодов на схеме, то можно заметить проблему. Пин номер 3 у части A и B один и тот же. На схеме соединяется пины 1 и 2. Получается, что два диода соединяются паралелльно и на встречу друг другу. Смысл этих диодов тогда пропадает. Подозреваю, что на схеме третий пин должен быть подключен к индуктивности.

**Comment by sintech** [comment]
Спасибо, исправил в a9cf7c198e970c73305a8bcc1b656d7e699d6c1c
В kicad библиотеках как раз обновилось УГО для BAV99.
